### ISSUE TITLE
Consolidate project name

### ISSUE THREAD

**Issue by ignasi35** [lagom/akka-discovery-service-locator#3]
While the main class is `AkkaDiscoveryServiceLocator` the project name in GitHub is `service-locator-akka-discovery`. We should consolidate to `akka-discovery-service-locator` since `akka-discovery` is an implementation detail and `service-locator` the exposed API.

**Comment by dwijnand** [comment]
Sounds right to me.

**Comment by octonato** [comment]
On the other hand, if we want it to have the features that is now provided by reactive-lib, we should instead have another name for it. 

This will not only be about service locator, but also the Cluster Bootstrap. Or, we need yet another project just for the bootstrap. 

I think personally that another project is overkill. We want an integration library that we can drop in any Lagom app and make it ready for production using Akka Cluster Bootstrap, Akka Discovery and Cluster Health Check. Basically, we want to rely on akka-management.

**Comment by dwijnand** [comment]
lagom-management?

**Comment by ignasi35** [comment]
I think it's not clear what this repo is for.

If we want a drop-in _thingy_ to take any lagom project into production then I think it should be split into several one-class artifacts. The reason is that [as a user I may only want the `AkkaDiscoveryServiceLocator` and not the `Bootstrap`](a custom case class).

```
lagom-javadsl-akka-discovery-service-locator // only the locator, no Module
lagom-javadsl-cluster-bootstrap // the bootstrap, the healthchecks and a Module
```

The reason why one has a `Module` and the other doesn't is that no `ServiceLocator` should be automatically bound (IMHO).

**Comment by ignasi35** [comment]
I haven't put too much thought on the proposal above, but splitting into modules and renaming the repo to `lagom-management` could keep things tidy.

Also, the above would also need `lagom-scaladsl-...` of course.

**Comment by dwijnand** [comment]
Yeah one repo, multiple modules.

**Comment by octonato** [comment]
Superseded by #9

**Comment by octonato** [comment]
The project is renamed to `akka-discovery-service-locator` as suggested here.
