### ISSUE TITLE
Investigate why bintray left a staging repository on sonatype for 0.0.12

### ISSUE THREAD

**Issue by marcospereira** [lagom/akka-discovery-service-locator#49]
When releasing Lagom, I've noticed that we still have a staging repository in Sonatype for this project, version 0.0.12. This is weird considering that we are not publishing to Sonatype directly, but instead, we are using Bintray to sync artifacts to maven central.

**Comment by dwijnand** [comment]
@2m or @raboof ever see this before?

**Comment by marcospereira** [comment]
To better explain the problem:

1. The artifact was published to maven central using Bintray
1. It can be seen in maven central now
1. And it also has a staging repository in Sonatype, for the same artifact published in maven central, created around the same time. This is the weird part.

It is possible this is a glitch in Bintray/Sonatype integration. I've dropped the staging repository to avoid conflicts when doing new releases, but this is something to pay attention for the next version of lagom-akka-discovery-service-locator.

**Comment by marcospereira** [comment]
For the record, here is the information for the staged repository:

Repository | comlightbend-1360 (com.lightbend)
-- | --
Created | Wednesday, February 06, 2019 11:50:41 EST (GMT-0500)
Updated | Wednesday, February 06, 2019 11:50:48 EST (GMT-0500)
Activity | Last operation completed successfully
Owner | marcospereira (75.126.118.182)
User-Agent | Apache-HttpClient/4.5 (Java/1.8.0_51)

**Comment by 2m** [comment]
The only thing that pops to my mind is the checkbox in bintray "Close and release repository when done" on the "Maven Central" tab. That one could have been unchecked during the release.

**Comment by octonato** [comment]
This can be closed now.
