### ISSUE TITLE
Rename Bootstrap 

### ISSUE THREAD

**Issue by ignasi35** [lagom/akka-discovery-service-locator#5]
[`Bootstrap`](https://github.com/lagom/service-locator-akka-discovery/blob/c087aa836e60369e24cd1d88ee0af76dd8950d4d/src/main/java/com/lightbend/lagom/javadsl/client/Bootstrap.java#L16-L24) could use a more meaningful name.

**Comment by dwijnand** [comment]
Suggestions?  Looks like it's doing some setting up and bootstrapping...

**Comment by ignasi35** [comment]
> Looks like it's doing some setting up and bootstrapping...

Maybe that's the problem.

`Bootstrap` starts Akka Management, Cluster Bootstrap and, by virtue of `application.conf` it starts Health checks. It's not obvious this is only meant for production or that it'll require akka cluster or, even more correct, lagom cluster (which is akka cluster on steroids).

Some users will not run Lagom clusterized because they have no persistence or pubsub and they may still want Healtchecks. Hmmm, I think `Bootstrap` should go away actually.

**Comment by octonato** [comment]
Superseded by #9
