### ISSUE TITLE
Use Akka ServiceName Parser

### ISSUE THREAD

**Issue by octonato** [lagom/akka-discovery-service-locator#61]
Akka 2.5.22 is scheduled on current akka team sprint plan. It it's out, we can remove the copy of the Service Name parser we have here.

**Comment by ignasi35** [comment]
@renatocaval Akka 2.5.22 is out.

**Comment by octonato** [comment]
For info, dependency already updated by @scala-steward in https://github.com/lagom/lagom-akka-discovery-service-locator/pull/73

**Comment by marcospereira** [comment]
@renatocaval was this fixed by #73 & #75?

**Comment by ignasi35** [comment]
It is.
