### ISSUE TITLE
Extract everything that is not ServiceLocator

### ISSUE THREAD

**Issue by octonato** [lagom/akka-discovery-service-locator#9]
The proposal is to have this project only containing the `ServiceLocator` implementation.

That `ServiceLocator` should become the prefered one for Lagom and users should configure the Akka Discovery mechanism used underneath. 

`reactive-lib` should depend on Akka Discovery and this `ServiceLocator` (see https://github.com/lightbend/reactive-lib/issues/101).

The Cluster Bootstrap should be moved to a new project `play-akka-cluster` so it can be used by Play directly.

The health-check added here becomes obsolete. It's now available in akka-management https://github.com/akka/akka-management/pull/393

**Comment by dwijnand** [comment]
> The Cluster Bootstrap should be moved to a new project `play-akka-cluster` so it can be used by Play directly.

(Maybe keep the "bootstrap" part? `play-cluster-bootstrap`/`play-akka-cluster-bootstrap`)

**Comment by octonato** [comment]
Good idea. 

I was in doubt if we should call it `play-cluster-bootstrap` or `play-akka-cluster`. 

I think it's ok to call it `play-cluster-bootstrap`.

**Comment by dwijnand** [comment]
Yeah it's similar to play-grpc, which is play + akka-grpc.

**Comment by TimMoore** [comment]
Looks like this was done in #12, correct?

**Comment by octonato** [comment]
yes, closing it.
